resolver: lts-23.19
packages:
- necrork
- necrork-cli
- necrork-gen

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages

extra-deps:
- github: NorfairKing/token-limiter-concurrent
  commit: fcc95f137696ddf23b63f32a6d697ba5a83a51b2
  subdirs:
    - token-limiter-concurrent
- github: NorfairKing/safe-coloured-text
  commit: 046f10147a058c00c2706d98c341219e3cbc7669
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: be4aba9ef133520a8a4087aa26915aaabf1376a7
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix

- github: NorfairKing/opt-env-conf
  commit: 2a6d3505aec34aacd2bc41d688fdf752815d9916
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/looper
  commit: eb24595196b08b0dcef7f6dbca65637cc26f8e6e
  subdirs:
    - looper
nix:
  enable: false
system-ghc: true
