name: necrork
version: 0.1.0.0
github: "NorfairKing/necrork"
license: AllRightsReserved
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2024 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- CHANGELOG.md

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - bytestring
    - containers
    - http-api-data
    - http-client
    - http-client-tls
    - looper
    - monad-logger
    - opt-env-conf
    - persistent
    - servant
    - servant-client
    - servant-client-core
    - text
    - time
    - token-limiter-concurrent
    - unliftio
    - validity
    - validity-text
